
Hands-on python challenges

In [2]:
# 1. write a python program to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n ** 0.5) + 1):
        if n % i == 0:
            return False
    return True


number = int(input("Enter a number:"))
print(f"{number} is prime: {is_prime(number)}")


5 is prime: True


In [6]:
#2. Create a FIbonacci sequence generator using recursion
def fibonacci(n):
    if n <= 1:
        return n
    return fibonacci(n - 1) + fibonacci(n - 2)


n = int(input("Enter the number of terms:"))
fib_sequence = [fibonacci(i) for i in range(n)]
print(fib_sequence)



[0, 1, 1, 2, 3]


In [7]:
#3. Write a function to find the greatest common divisor (GCD) and Least Common Multiple (LCM) of two numbers
def gcd(a, b):
    while b:
        a, b = b, a % b
    return a

def lcm(a, b):
    return a * b // gcd(a, b)

a = int(input("Enter the first number:"))
b = int(input("Enter the second number:"))
print(f"GCD of {a} and {b} is {gcd(a, b)}")
print(f"LCM of {a} and {b} is {lcm(a, b)}")

GCD of 10 and 25 is 5
LCM of 10 and 25 is 50


In [ ]:
#4. Build a simple calculator using functions
def add(x, y):
    return x + y

def subtract(x, y):
    return x - y

def multiply(x, y):
    return x * y

def divide(x, y):
    if y == 0:
        return "Cannot divide by zero"
    return x / y

a = int(input("Enter the first number:"))
b = int(input("Enter the second number:"))
print("Add:", add(a, b))
print("Subtract:", subtract(a, b))
print("Multiply:", multiply(a, b))
print("Divide:", divide(a, b))


In [10]:
# 5. Implement a program that takes a list and removes duplicates.
def remove_duplicates(lst):
    return list(set(lst))

lst = list(map(int, input("Enter the list of numbers:").split()))
print("List after before duplicates:" ,lst)
print( "List after removing duplicates" ,remove_duplicates(lst))

List after before duplicates: [1, 1, 1, 2, 3, 4, 2, 3]
List after removing duplicates [1, 2, 3, 4]


In [11]:
# 6. Create a dictionary, add five key-value pairs, and print them

my_dict = {
    'name': 'John Doe',
    'age': 19,
    'city': 'Hyderabad',
    'job': 'Student',
    'country': 'India'
}

for key, value in my_dict.items():
    print(f"{key}: {value}")


name: John Doe
age: 19
city: Hyderabad
job: Student
country: India


In [12]:
#7. Use NumPy to perform basic matrix operations.
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

matrix_sum = A + B
matrix_diff = A - B
matrix_product = np.dot(A, B)
matrix_transpose = np.transpose(A)

print("Matrix Sum:\n", matrix_sum)
print("Matrix Difference:\n", matrix_diff)
print("Matrix Product:\n", matrix_product)
print("Matrix Transpose:\n", matrix_transpose)


Matrix Sum:
 [[ 6  8]
 [10 12]]
Matrix Difference:
 [[-4 -4]
 [-4 -4]]
Matrix Product:
 [[19 22]
 [43 50]]
Matrix Transpose:
 [[1 3]
 [2 4]]


In [13]:
#8. Read a CSV file using pandas and display the first 5 rows.
import pandas as pd
data = pd.read_csv('data.csv')
print(data.head())

   id        name  class  mark  gender
0   1    John Deo   Four    75  female
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female


In [16]:
#9. Write a function that finds the most common word in a given text.
def most_common_word(text):
    words = text.split()
    word_count = {}
    for word in words:
        if word in word_count:
            word_count[word] += 1
        else:
            word_count[word] = 1
    return max(word_count, key=word_count.get)

text = input("Enter the text:")
print("input text:", text)
print("Most common word:", most_common_word(text))

input text: Hello World, Hello Universe
Most common word: Hello


In [22]:
#10. Create a function that generates a random password with a mix of uppercase, lowercase, digits, and special characters.
import random
import string
def generate_password(length=8):
    characters = string.ascii_letters + string.digits + string.punctuation
    password = ''.join(random.choice(characters) for i in range(length))
    return password

print("Random Password:", generate_password(12))


Random Password: 455*g5E&6fGb
